<?php
/**
 * Technooze_Stores extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Technooze
 * @package    Technooze_Stores
 * @copyright  Copyright (c) 2008 Technooze LLC
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * @category   Technooze
 * @package    Technooze_Stores
 * @author     Technooze <info@technooze.com>
 */
?>
<div id="store_search">
<?php $store_locations = (array)Mage::registry('store_locations'); ?>
<?php if(!empty($store_locations)): ?>
	<ul class="dotted_list closeby">
        <li class="clearer th-header">
            <span class="distance"><span>Distance</span></span>
            <span class="address"><span>Address</span></span>
            <span class="phone"><span>Phone</span></span>
            <span class="info"><span>Info</span></span>
            <span class="links"><span>Links</span></span>
        </li>
		<?php foreach($store_locations as $k => $v): ?>
        <li class="clearer td-content oe-<?php echo ($k++%2); ?> store-<?php echo $k; ?>">
            <span class="distance"><span><?php echo round($v['distance'], 2); ?>KM</span></span>
            <span class="address"><span><?php echo nl2br(str_replace(',', ', ',$v['address_display'])); ?></span></span>
            <span class="phone"><span><?php echo $v['phone']; ?></span></span>
            <span class="info"><span><a title="View <?php echo $v['title']; ?> details" href="<?php echo $this->getUrl() . $v['url_key']; ?>.html" class="cta">Details</a></span></span>
            <span class="links"><span>Catalogues</span></span>
        </li>
    	<?php endforeach; ?>
	</ul>
<?php else: ?>
	<div class="no-stores">
        <p>
            No stores found close to this store.
        </p>
    </div>
<?php endif; ?>
</div>